In [6]:
course = {
  "954340": "Enterprise Database",
  "954471": "Business Data Mining",
  "954472": "Business Data Visualization"
}
print(course)

{'954340': 'Enterprise Database', '954471': 'Business Data Mining', '954472': 'Business Data Visualization'}

In [7]:
course.keys()

dict_keys(['954340', '954471', '954472'])

In [8]:
#Example 6
sorted(course.values())

['Business Data Mining', 'Business Data Visualization', 'Enterprise Database']

In [13]:
L = ["A", "B", "C" ,"D"]
a = [item for item in L]
a

['A', 'B', 'C', 'D']

In [16]:
a = [item*5 for item in L if item is not 'C']
a

['AAAAA', 'BBBBB', 'DDDDD']

In [17]:
a = [item+i2 for item in L for i2 in L]
a

['AA',
 'AB',
 'AC',
 'AD',
 'BA',
 'BB',
 'BC',
 'BD',
 'CA',
 'CB',
 'CC',
 'CD',
 'DA',
 'DB',
 'DC',
 'DD']

In [20]:
L = ["A", "B", "C" , "D"]
a = [item for item in L if item not in [ 'A','B','D']]
a

['C']

In [40]:
def summation(L):
    sum = 0
    for item in L:
        sum = sum + item
    return sum
summation([1,2,3,4,5,6,7,8,9,10])

55

In [39]:
def multi(start, end):
    for i in range(start, end+1):
        for j in range(12):
            print(str(i)+"x"+str(j+1),"=",str(i*(j+1)))
        print("\n")
multi(3,6)

3x1 = 3
3x2 = 6
3x3 = 9
3x4 = 12
3x5 = 15
3x6 = 18
3x7 = 21
3x8 = 24
3x9 = 27
3x10 = 30
3x11 = 33
3x12 = 36


4x1 = 4
4x2 = 8
4x3 = 12
4x4 = 16
4x5 = 20
4x6 = 24
4x7 = 28
4x8 = 32
4x9 = 36
4x10 = 40
4x11 = 44
4x12 = 48


5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
5x10 = 50
5x11 = 55
5x12 = 60


6x1 = 6
6x2 = 12
6x3 = 18
6x4 = 24
6x5 = 30
6x6 = 36
6x7 = 42
6x8 = 48
6x9 = 54
6x10 = 60
6x11 = 66
6x12 = 72

# Assignment 2.1

In [37]:
n = 20
for i in range(n+1):
    print("<3" * i)

<3
<3<3
<3<3<3
<3<3<3<3
<3<3<3<3<3
<3<3<3<3<3<3
<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3

# Assignment 2.2

In [33]:
n = [1,2,3,4,5,6,7,8,9,]
odd = [num for num in n if num%2 == 1]
count = len(odd)
print("Number of even numbers : ",len(n)- count)
print("Number of odd numbers : ",count)

Number of even numbers :  4
Number of odd numbers :  5